config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  
  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    # get 'login', to: "devise/sessions#new", as: "login"
    # get 'logout', to: "devise/sessions#destroy", as: "logout"
    # get 'logout', to: "users/sessions#destroy", as: "logout"
    get '/users/sign_out' => 'devise/sessions#destroy' 
    get 'signup', to: "users#new", as: "signup"
    # match '/users/:id', :to => 'users#show', :as => :user
  end

  resources :users
  # resources :surveys
  get "/testing", to: "surveys#testing"
  resources :surveys do
    resources :pages
    put :customize_final_page
    get :final_page
    get :fill
    post :post_answer
  end
  get '/page_question/:id/:page_id' ,to:  "pages#page_questions" ,:as => "page_questions"
  post 'save_page_question/:survey_id/:page_id' , to: "questions#create" , :as => "create_page_question"
  get 'questions/:id/destroy/:page_id' , to: "questions#destroy" , :as => "delete_question_page"
  get 'questions/:id/copy/:page_id' , to: "questions#copy" , :as => "copy_question_page"
  get 'questions/:id/edit/:page_id' , to: "questions#edit" , :as => "edit_question_page"
  put 'questions/update' , to: "questions#update" , :as => "update_question_page"
  get 'questions/:id/move/:page_id/:survey_id' , to: "questions#move" , :as => "move_question_page"
  put 'page/update' , to: "pages#update" , :as => "update_page"
  get 'page/:id/copy' , to: "pages#copy" , :as => "copy_page"
  get 'page/:id/move/:survey_id' , to: "pages#move" , :as => "move_page"
  get 'survey/:id/logical_workflow' , to: "surveys#logical_workflow" , :as => "logical_workflow_survey"
  post 'survey/:id/save_logical_workflow' , to: "surveys#save_logical_workflow" , :as => "save_logical_workflow_survey"
  get 'survey/:id/layout_coloring' , to: "surveys#layout_coloring" , :as => "layout_coloring_survey"
  post 'survey/:id/save_layout_coloring' , to: "surveys#save_layout_coloring" , :as => "save_layout_coloring_survey"
  post 'next_question_logical_workflow/:id/' , to: "surveys#next_question_logical_workflow" , :as => "next_question_logical_workflow"
  get 'customer_surveys/:id' , to: "customer_surveys#survey" , :as => "customer_survey"

  resources :reports 
  get 'report/:id/:type' , to: "reports#download" , :as => "download_reports"

  root to: 'visitors#index'
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    @status,@message = Question.save_with_detail(params)
    @page_id = params[:page_id]
    @page = Page.find(@page_id)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    question = Question.find(params[:id])
    @page_id = params[:page_id]
    @page = Page.find(@page_id)

    respond_to do |format|
      format.js if question.destroy
    end
  end

  def copy
    question = Question.find(params[:id])
    @page_id = params[:page_id]
    @page = Page.find(@page_id)
    new_question = question.dup
    respond_to do |format|
      format.js if new_question.save!
    end
  end

  def edit
    @question = Question.find(params[:id])
    @page_id = params[:page_id]
    @page = Page.find(@page_id)
    time = Time.new
    @index = time.to_i
    respond_to do |format|
      format.js
    end
  end

  def update
    if params[:move].present?
      @status,@message, @page_id , @prev_page_id = Question.move_question(params)
      @prev_page = Page.find(@prev_page_id)
      @view_type = "move"
    else
      @status,@message, @page_id , @question = Question.update_with_detail(params)
      @view_type = "update"
    end
    @page = Page.find(@page_id)
    respond_to do |format|
      format.js
    end
  end

  def move
    @pages = Page.where("survey_id = ? and id != ? ", params[:survey_id],params[:page_id])
    @question_id = params[:id]
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def generate_choise(type,data, has_na=false, na_value='',processed_view)
    choise_name = processed_view.blank? ? "" : "choise_answer[#{data.id}][]"
    if type =="dropdown"
      
      option = data.choise.split(/\n/)
      style = "background-color:#{data.page.survey.layout_colorings.first.row_color}" unless processed_view.blank?
      select_tag "#{choise_name}", options_for_select(option) ,:class => "choise_answer_#{data.id}",:style => style

    elsif type =="dropdown_rangking"
      
      value_rating = []
      style = "background-color:#{data.page.survey.layout_colorings.first.row_color}" unless processed_view.blank?
      options = data.choise.split(/\n/)
      options.each_with_index{|op,idx| value_rating << idx+1 }
      rangking_opt = has_na ? value_rating+[na_value] : value_rating
      opt = '<ul class="dropdown-ranking-select- rangking-list unstyled" style="margin-left: 0;"  >'
      options.each do |s|
        opt += "<li style=#{style}> <i class='fa fa-sort icons-move handle'></i> "
        opt += select_tag "#{choise_name}", options_for_select(rangking_opt),:class => "choise_answer_#{data.id}"
        opt += "<span class='ranking-question'>#{s}</span> </li>"
      end
      opt +='</ul>'
      raw(opt)
    elsif type=="multiline_text_box"
        text_area_tag("#{choise_name}", data.default_value, style: "#{data.inline_style}")
    elsif type == "evaluation1" || type == "evaluation2" || type == "multiple_answer"
      row = data.choise.split(/\n/)
      column = data.column_label.split(/\n/)
      generateTabel(row,column,type, data)
    elsif type == "multiple_choice" || type == "radio_box"
      row = data.choise.split(/\n/)
      opt = '<ul class="dropdown-ranking-select- rangking-list unstyled" style="margin-left: 0;" >'
      row.each_with_index do |s,index|
        opt += "<li> <i class='fa fa-sort icons-move handle'></i>"
        opt += check_box("choise_answer[#{data.id}]","#{index}",{},s) if type == "multiple_choice"
        opt += radio_button "choise_answer" ,"#{data.id}",s,:class => "choise_answer_#{data.id}"  if type == "radio_box"
        opt += " <span class='ranking-question'>#{s}</span> </li>"
      end
      opt += "<li>"
      opt += check_box("choise_answer[#{data.id}]" ,"#{row.count}",{},"input") if type == "multiple_choice"
      opt += radio_button("choise_answer[#{data.id}]" ,"#{row.count}","input") if type == "radio_box"
      opt += "#{data.column_label} <input type='text' value=''  name='input_answer[#{type}][#{data.id}]'> </li>" 
      opt +='</ul>'
      raw(opt)
    elsif type == "yes_no"
      opt = '<ul class="dropdown-ranking-select- rangking-list unstyled" style="margin-left: 0;" >'
      opt += "<li>"
      opt += radio_button("choise_answer" ,data.id,'0' ,:class => "choise_answer_#{data.id}") 
      opt += "<span class='ranking-question'>Yes </span> </li>"
      opt += "<li>"
      opt += radio_button("choise_answer" ,data.id,'1' ,:class => "choise_answer_#{data.id}")
      opt += "<span class='ranking-question'>No </span> </li>"
      opt += "</ul>"
      raw(opt)
    elsif type == 'percentage'
      opt = '<h4 class="color-black dropdown-question-" data-placement="top" data-toggle="tooltip" href="#" data-original-title=""></h4>'
      opt += "<div>"
      opt += "<span class='pbefore-1 color-black'>#{data.text_before_field}</span>"
      opt += '<input type="range" min="0" max="100" value="1" class="percentage-1">'
      opt += "<span class='pafter-1 color-black'>#{data.text_after_field}</span>"
      opt += "</div>"
      raw(opt)

    elsif type == 'single_question'
      opt = "<input type='text' name='#{choise_name}' style='#{data.inline_style}' value='#{data.default_value}' />"
      raw(opt)
    end
  end

  def generate_choise_for_answer_survey(type,data)
    if type =="dropdown" 
      option = data.split(/\n/)
      select_tag 'choise', options_for_select(option)
    elsif type =="dropdown_rangking"
      rangking_opt = [1,2]
      options = data.split(/\n/)
      opt = '<ul class="dropdown-ranking-select- rangking-list unstyled" style="margin-left: 0;" >'
      options.each do |s|
        opt += "<li> <i class='fa fa-sort icons-move handle'></i>  #{select_tag '', options_for_select(rangking_opt)} <span class='ranking-question'>#{s}</span> </li>"
      end
      opt +='</ul>'
      raw(opt)
    elsif type=="multiline_text_box"
        text_area_tag("multiline_text_box", data.default_value, style: "#{data.inline_style}")
    elsif type == "evaluation1" || type == "evaluation2" || type == "multiple_answer"
      row = data.choise.split(/\n/)
      column = data.column_label.split(/\n/)
      generateTabel(row,column,type)

    elsif type == "multiple_choice" || type == "radio_box"
      row = data.choise.split(/\n/)
      opt = '<ul class="dropdown-ranking-select- rangking-list unstyled" style="margin-left: 0;" >'
      row.each do |s|
        opt += "<li> <i class='fa fa-sort icons-move handle'></i>"
        opt += check_box('','multiple_choice') if type == "multiple_choice"
        opt += radio_button("question[#{data.id}]",'radio_box', s) if type == "radio_box"

        opt += " <span class='ranking-question'>#{s}</span> </li>"
      end
      opt += "<li>"
      opt += check_box('','multiple_choice') if type == "multiple_choice"
      opt += radio_button("question[#{data.id}]" ,'radio_box','') if type == "radio_box"

      opt += "#{data.column_label} <input type='text' value=''  name=''> </li>"
      opt +='</ul>'
      raw(opt)
    elsif type == "yes_no"
      opt = '<ul class="dropdown-ranking-select- rangking-list unstyled" style="margin-left: 0;" >'
      opt += "<li>"
      opt += radio_button("question[#{data.id}]", 'radio_box', 'Yes') 
      opt += "<span class='ranking-question'>#{t(:yes_label)} </span> </li>"
      opt += "<li>"
      opt += radio_button("question[#{data.id}]", 'radio_box', 'No')
      opt += "<span class='ranking-question'>#{t(:no_label)} </span> </li>"
      opt += "</ul>"
      raw(opt)
    end
  end

  def generateTabel(row,column,type,data=0)
    render :partial => "questions/generateTabel",:locals => {:row => row , :col => column ,:type => type, data: data}
  end

  def setValueQuestion(data,name,type)
    value = ""
    unless data.blank?
      value = data.name if name == "name"
      value = data.tooltips if name == "tooltips"
      if name == "first_choise"
        choise = data.choise.split(/\n/)
        value = choise[0]
      end
      if name == "choise"
        value = setValueQuestionChoise(data,type)
      end
    end
    return value
  end

  def setValueQuestionChoise(data,type)
    value = valueChoiseWithoutFirstElement(data) if type == "dropdown"
    value = data.choise if type == "evaluation1" || type == "dropdown_rangking" || type == "evaluation2" || type == 'multiline_text_box' || type == 'multiple_answer'

    return value
  end

  def valueChoiseWithoutFirstElement(data)
    value = ""
    data.choise.split(/\n/).each_with_index do |d,idx|
      unless idx == 0
        value +="#{d}\n " unless d.blank?
      end
    end
    return value
  end

  def generateLogicalView(data,logical_array)
    list_answers = {}
    new_logical_array = []
    value_options = {}
    unless data.question_type =="yes_no"
      list_answers = data.choise.split(/\n/) 
      list_answers.delete_at(0) if data.question_type=="dropdown"
    end
    list_answers = ["yes","no"] if data.question_type =="yes_no"
    logical_array.each{|d| new_logical_array << [truncate(d[0], length: 40),d[1]] unless d.include?(data.id) }
    new_logical_array << ["Final Page",99999]
    list_answers.each_with_index do |la,index|
      value = LogicalWorkflow.where(:question_id => data.id , :choise_index => index)

      value_options["#{index}"] =  (value.blank? ? " " : value.first.choise_question_id)
    end
    render :partial => "surveys/logical_view" ,:locals => {:list_answers => list_answers ,:logical_array => new_logical_array,:data => data,:value_options => value_options }

  end

  def layout_coloring(survey,data,proccessed_view)
    style = []
    layout = survey.layout_colorings.first
    unless layout.blank?  
      unless proccessed_view.blank?
        data.each do |d|
          style << "color:#{layout.font_color}" if d == "font_color"
          style << "background-color:#{layout.background_color}" if d == "background_color" 
          style << "color:#{layout.button_font_color}" if d == "button_font_color"
          style << "background-color:#{layout.button_background_color}" if d == "button_background_color" 
          style << "border-color:#{layout.button_border_color}" if d == "button_border_color" 

          style << 'border-style: solid' if d == "top_border_color"
          style << 'border-width: 4px' if d == "top_border_color"
          style << "border-top-color:#{layout.top_border_color}" if d == "top_border_color"

          style << "border-bottom-color:#{layout.bottom_border_color}" if d == "bottom_border_color" 
          style << "border-right-color:#{layout.right_border_color}" if d == "right_border_color" 
          style << "border-left-color:#{layout.left_border_color}" if d == "left_border_color" 
          style << "width:#{layout.width_box}px" if d == "width_box" 
          style << "height:#{layout.height_box}px" if d == "height_box" 
          

        end 
      end
    end
    join_style = style.join(";")
    layout_style = "style=\'#{join_style}\'"

    raw layout_style
  end

  def generateLogicalDropdown(survey)

  end

end

app/views/questions/_actionPerQuestion.html.erb
 <%= link_to(raw('<i class="halflings-icon white edit"></i>'),edit_question_page_path(question.id,question.page_id),remote: true, :class=> "btn" ) %>
 <%= link_to(raw('<i class="halflings-icon white move"></i>'),move_question_page_path(question.id,question.page_id,question.page.survey_id),remote: true, :class=> "btn btn-primary move_question " ) %>
 <%= link_to(raw('<i class="halflings-icon white share-alt"></i>'),copy_question_page_path(question.id,question.page_id),remote: true,:data => {:confirm => 'Are you sure to copy ?'} , :class=> "btn btn-success" ) %>
 <%#= link_to(raw('<i class="halflings-icon white wrench"></i>'),'#',remote: true, :class=> "btn btn-warning" ) %>
 <%= link_to(raw('<i class="halflings-icon white remove"></i>'),delete_question_page_path(question.id,question.page_id),remote: true, :data => {:confirm => 'Are you sure to delete?'} ,:class=> "btn btn-danger" ) %>

app/views/questions/_evaluation2.html.erb
<div class="task low wrapper_<%=page_id%>">
  <div class="desc">
    <div class="title">Evaluation 2</div>
    <div>

      <div class="control-group">
        <label class="control-label">Question <span class="mark-required">*</span></label>
        <div class="controls ">
          <textarea class="input-xlarge span12 text-preview text-eval-<%=index%>" name="question[name][]" data-index="<%=index%>" data-target="dropdown-question-"><%=setValueQuestion(question,"name","evaluation2")%></textarea>
          <input type="hidden" name="question[question_type][]" value="evaluation2" >
          <input type="hidden" name="question_index[]" value="<%=index%>" >
        </div>
      </div>  
                
      <div class="control-group">
        <label class="control-label">
          Individual Note 
          <span class="pull-right"><input type="checkbox" name="question[check_tooltip][]" class="is-tooltip" data-index="<%=index%>" data-target="dropdown-question-" data-value-from="note-<%=index%>"/> Show as tooltip</span>
        </label>
        <div class="controls ">
          <input class="input-xlarge span12 note-preview note-<%=index%>" data-index="<%=index%>" data-target="dropdown-question-" name="question[tooltips][]" type="text" value="<%=setValueQuestion(question,"tooltips","evaluation2")%>"/>
        </div>
      </div>  

      <div class="control-group">
        <label class="control-label">Answer fields <span class="mark-required">*</span></label>
        <div class="controls">
          <div class="span4">
            <textarea class="input-xlarge eval2 span12 eval1-preview text-eval1-<%=index%>" name="question[choise][]" data-index="<%=index%>" data-target="eval-prev-" rows="5"><%=setValueQuestion(question,"choise","evaluation2")%></textarea>
            <p class="help-block">Separate each item by line break</p>
          </div>
          <div class="span8">
            <div class="eval1check">
              <input type="checkbox" name="append_open_box" data-index="<%=index%>" data-target="foot-eval1-" class="eval1-check"/>
              Append open inbox box
            </div>
            <div class="span5 hide foot-eval1-<%=index%>">
              <p class="label-eval">Text before optional text field</p>
              <input type="text" name="text_before_field" class="span12 eval1-foot-label" data-index="<%=index%>" data-target="foot-eval1-label-" value="<%= question.try(:text_before_field)%>"/>
            </div>      
            <div class="span5 hide foot-eval1-<%=index%>">
              <p class="label-eval">Text box width</p>
              <input type="text" name="inline_style" class="span4 eval1-width" data-index="<%=index%>" data-target="optional-eval1-"/><span> px</span>
            </div>

            <!-- column -->
            <div class="span3">
              <p class="label-eval">Number of column</p>
              <select class="span5 eval1-column evals-column-<%=index%>" data-index="<%=index%>" data-target="column-eval1-" name="column_count">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3" selected="selected">3</option>
              </select>
            </div>
            <div class="span8">
              <p class="label-eval">Column label:</p>
              <input type="text" name="question[column_label][<%=index%>][]" class="span4 label-eval1 column-eval1-<%=index%> col1" data-index="<%=index%>" value="Column 1"/>
              <input type="text" name="question[column_label][<%=index%>][]" class="span4 label-eval1 column-eval1-<%=index%> col2" data-index="<%=index%>" value="Column 2"/>
              <input type="text" name="question[column_label][<%=index%>][]" class="span4 label-eval1 column-eval1-<%=index%> col3" data-index="<%=index%>" value="Column 1"/>
            </div>

            <!-- last column checxbox -->
            <div class="span12">
              <input type="checkbox" name="tobechanged"/>
              The last column is a "No answer" column (or equivalent) and is not considered in the evaluation
            </div>

            <div class="span12">
              <p class="label-eval">Description of block "Weighting"</p>
              <input type="text" name="question[description_block][]" class="weighting" data-index="<%=index%>" value="weighting" />
            </div>
          </div>
        </div>
      </div> 

      <div class="control-group" style="clear:both">
        <div class="box black">
          <div class="box-header">
            <h2>Preview of question</h2>
          </div>
          <div class="box-content preview">
            <h4 class="color-black dropdown-question-<%=index%>" data-placement="top" data-toggle="tooltip" href="#" data-original-title=""></h4>
            <div>
              <table style="width:100%">
                <thead>
                  <tr>
                    <td colspan="5"></td>
                    <td colspan="4" class="color-black weighting-<%=index%>" align="center">Weighting</td>
                  </tr>
                  <tr>
                    <td width="42%">
                     
                    </td>
                    <td class="color-black label-eval1-<%=index%> column-eval1-<%=index%> col1" width="10%">
                      Column 1
                    </td>
                    <td class="color-black label-eval1-<%=index%> column-eval1-<%=index%> col2" width="10%">
                      Column 2
                    </td>
                    <td class="color-black label-eval1-<%=index%> column-eval1-<%=index%> col3" width="10%">
                      Column 3
                    </td>
                    <td width="10%"></td>
                    <td class="color-black" width="7%">--</td>
                    <td class="color-black" width="7%">-</td>
                    <td class="color-black" width="7%">+</td>
                    <td class="color-black" width="7%">++</td>
                  </tr>
                </thead>
                <tbody class="eval-list eval-prev-<%=index%>" data-index="<%=index%>">
                 
                </tbody>
                <tfoot class="hide foot-eval1-<%=index%>">
                  <tr>
                    <td>
                      <span class="foot-eval1-label-<%=index%> color-black"></span>
                      <input type="text" name="prev" class="optional-eval1-<%=index%>"/>
                    </td>
                    <td class="column-eval1-<%=index%> col1">
                      <label class="radio ">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                    <td class="column-eval1-<%=index%> col2">
                      <label class="radio">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                    <td class="column-eval1-<%=index%> col3">
                      <label class="radio">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                    <td></td>
                    <td>
                      <label class="radio">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                    <td>
                      <label class="radio">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                    <td>
                      <label class="radio">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                    <td>
                      <label class="radio">
                        <input type="radio" name="foot" value="option2">
                      </label>
                    </td>
                  </tr>
                </tfoot>
              </table>
              <p class="help-block note-block-<%=index%>"></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="time">
    <div class="date"> 
      <button class="btn btn-danger"><i class="halflings-icon white remove"></i></button>
    </div>
    <div> -- </div>
  </div>
</div>

<script>
$(".eval-list").sortable({
  handle: ".handle",
  update: function(event, ui) {
    var idx, text;
    text = "";
    idx = $(this).attr('data-index');
    $(".eval-item-" + idx).each(function(i) {
      text += $(this).attr('data-value');
      return text += "\n";
    });
    return $(".text-eval1-" + idx).val(text.trim());
  }
});
</script>

app/views/questions/_file_upload.html.erb
<div class="task low">
  <div class="desc">
    <div class="title">File Upload</div>
    <div>

      <div class="control-group">
        <label class="control-label">Question <span class="mark-required">*</span></label>
        <div class="controls ">
          <textarea class="input-xlarge span12 text-preview text-eval-3" name="text" data-index="3" data-target="dropdown-question-"></textarea>
        </div>
      </div>  
                
      <div class="control-group">
        <label class="control-label">
          Individual Note 
          <span class="pull-right"><input type="checkbox" name="tooltip" class="is-tooltip" data-index="3" data-target="dropdown-question-" data-value-from="note-3"/> Show as tooltip</span>
        </label>
        <div class="controls ">
          <input class="input-xlarge span12 note-preview note-3" data-index="3" data-target="dropdown-question-" name="text" type="text" />
        </div>
      </div>  

      <div class="control-group">
        <label class="control-label">"Browse" Button</label>
        <div class="controls ">
          <input class="input-xlarge span6 browse_btn" type="text" data-index="3" data-target="upload-btn-" value="Browse.." name="tobechanged" />
        </div>
      </div>


      <div class="control-group">
        <label class="control-label">Maximum file size</label>
        <div class="controls ">
          <select class="input-xlarge" name="tobechanged">
            <option value="1"><= 1MB</option>
            <option value="5"><= 5MB</option>
            <option value="10"><= 10MB</option>
            <option value="50"><= 50MB</option>
          </select>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Accepted formats (<a class="selectAll">Select all</a><a class="deselectAll"> Deselect all</a>)</label>
        <div class="controls checkboxes">
          <input type="checkbox" name="csv"> csv
          <input type="checkbox" name="doc"> doc/docx
          <input type="checkbox" name="pdf"> pdf
          <input type="checkbox" name="ppt"> pps/ppt/pptx
          <input type="checkbox" name="txt"> txt
          <input type="checkbox" name="xls"> xls/xlxs
          <input type="checkbox" name="mp3"> mp3
          <input type="checkbox" name="wav"> wav
          <input type="checkbox" name="wma"> wma
          <input type="checkbox" name="avi"> avi
          <input type="checkbox" name="flv"> flv
          <input type="checkbox" name="m4v"> m4v
          <input type="checkbox" name="mov"> mov
          <input type="checkbox" name="mp4"> mp4
          <input type="checkbox" name="mpeg"> mpeg
          <input type="checkbox" name="bmp"> bmp
          <input type="checkbox" name="gif"> gif
          <input type="checkbox" name="jpg"> jpg/jpeg
          <input type="checkbox" name="png"> png
          <input type="checkbox" name="tif"> tif/tiff
          <input type="checkbox" name="ico"> ico
          <input type="checkbox" name="rar"> rar
          <input type="checkbox" name="zip"> zip
        </div>
      </div>  

      <div class="control-group" style="clear:both">
        <div class="box black">
          <div class="box-header">
            <h2>Preview of question</h2>
          </div>
          <div class="box-content preview">
            <h4 class="color-black dropdown-question-3" data-placement="top" data-toggle="tooltip" href="#" data-original-title=""></h4>
            <div>
              <p class="help-block note-block-3"></p>
            </div>
            <div style="margin-top:20px">
              <button class="btn btn-primary uploads upload-btn-3">Browse..</button>
              <input type="file" class="hidden file_upload" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="time">
    <div class="date"> 
      <button class="btn btn-danger"><i class="halflings-icon white remove"></i></button>
    </div>
    <div> -- </div>
  </div>
</div>

app/views/questions/_list_evaluation1.html.erb
<div class="desc">
  <div class="title <%= question.as_tooltips? ? 'tooltips': ''%>" data-placement="right" data-toggle="tooltip" href="#" data-original-title="<%= question.tooltips%>"> <%=index+1%>. <%=question.question%></div>
  <div>
    <%=generate_choise(question.question_type,question,proccessed_view)%>
  </div>
  <% unless question.as_tooltips %>
    <p><%=question.tooltips%></p>
  <% end %>
</div>

app/views/questions/_list_evaluation2.html.erb
<div class="desc">
  <div class="title <%= question.as_tooltips? ? 'tooltips': ''%>" data-placement="right" data-toggle="tooltip" href="#" data-original-title="<%= question.tooltips%>"> <%=index+1%>. <%=question.question%></div>
  <div>
    <%=generate_choise(question.question_type,question,proccessed_view)%>
  </div>
  <% unless question.as_tooltips %>
    <p><%=question.tooltips%></p>
  <% end %>
</div>

app/views/questions/_list_multiline_text_box.html.erb
<div class="desc">
  <div class="title <%= question.as_tooltips? ? 'tooltips': ''%>" data-placement="right" data-toggle="tooltip" href="#" data-original-title="<%= question.tooltips%>"> <%=index+1%>. <%=question.question%></div>
  <div>
    <%=generate_choise(question.question_type,question,proccessed_view)%>
  </div>
  <% unless question.as_tooltips %>
    <p><%=question.tooltips%></p>
  <% end %>
</div>

app/views/questions/_list_multiple_answer.html.erb
<div class="desc">
  <div class="title <%= question.as_tooltips? ? 'tooltips': ''%>" data-placement="right" data-toggle="tooltip" href="#" data-original-title="<%= question.tooltips%>"> <%=index+1%>. <%=question.question%></div>
  <div>
    <%=generate_choise(question.question_type,question,proccessed_view)%>
  </div>
  <% unless question.as_tooltips %>
    <p><%=question.tooltips%></p>
  <% end %>
</div>

app/views/questions/_list_radio_box.html.erb
<div class="desc">
  <div class="title <%= question.as_tooltips? ? 'tooltips': ''%>" data-placement="right" data-toggle="tooltip" href="#" data-original-title="<%= question.tooltips%>"> <%=index+1%>. <%=question.question%></div>
  <div>
    <%=generate_choise(question.question_type,question,proccessed_view)%>
  </div>
  <% unless question.as_tooltips %>
    <p><%=question.tooltips%></p>
  <% end %>
</div>