config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  
  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    # get 'login', to: "devise/sessions#new", as: "login"
    # get 'logout', to: "devise/sessions#destroy", as: "logout"
    # get 'logout', to: "users/sessions#destroy", as: "logout"
    get '/users/sign_out' => 'devise/sessions#destroy' 
    get 'signup', to: "users#new", as: "signup"
    # match '/users/:id', :to => 'users#show', :as => :user
  end

  resources :users
  # resources :surveys
  get "/testing", to: "surveys#testing"
  resources :surveys do
    resources :pages
    put :customize_final_page
    get :final_page
    get :fill
    post :post_answer
  end
  get '/page_question/:id/:page_id' ,to:  "pages#page_questions" ,:as => "page_questions"
  post 'save_page_question/:survey_id/:page_id' , to: "questions#create" , :as => "create_page_question"
  get 'questions/:id/destroy/:page_id' , to: "questions#destroy" , :as => "delete_question_page"
  get 'questions/:id/copy/:page_id' , to: "questions#copy" , :as => "copy_question_page"
  get 'questions/:id/edit/:page_id' , to: "questions#edit" , :as => "edit_question_page"
  put 'questions/update' , to: "questions#update" , :as => "update_question_page"
  get 'questions/:id/move/:page_id/:survey_id' , to: "questions#move" , :as => "move_question_page"
  put 'page/update' , to: "pages#update" , :as => "update_page"
  get 'page/:id/copy' , to: "pages#copy" , :as => "copy_page"
  get 'page/:id/move/:survey_id' , to: "pages#move" , :as => "move_page"
  get 'survey/:id/logical_workflow' , to: "surveys#logical_workflow" , :as => "logical_workflow_survey"
  post 'survey/:id/save_logical_workflow' , to: "surveys#save_logical_workflow" , :as => "save_logical_workflow_survey"
  get 'survey/:id/layout_coloring' , to: "surveys#layout_coloring" , :as => "layout_coloring_survey"
  post 'survey/:id/save_layout_coloring' , to: "surveys#save_layout_coloring" , :as => "save_layout_coloring_survey"
  post 'next_question_logical_workflow/:id/' , to: "surveys#next_question_logical_workflow" , :as => "next_question_logical_workflow"
  get 'customer_surveys/:id' , to: "customer_surveys#survey" , :as => "customer_survey"

  resources :reports 
  get 'report/:id/:type' , to: "reports#download" , :as => "download_reports"

  root to: 'visitors#index'
end

app/views/pages/_detail.html.erb
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div data-original-title="" class="box-header">
      <h2>
        <i class="halflings-icon notes_2"></i>
        <span class="break"></span>
        <%= page.page_title %>
      </h2>
      <div class="box-icon">
        <%= link_to(raw('<i class="halflings-icon edit"></i>'),edit_survey_page_path(page.survey_id,page.id),remote: true, :class=> "btn-setting" ) %>

        <%= link_to(raw('<i class="halflings-icon move"></i>'),move_page_path(page.id,page.survey_id),remote: true, :class=> "btn-setting" ) %>

        <%= link_to(raw('<i class="halflings-icon share-alt"></i>'),copy_page_path(page.id),remote: true, method: :get, :data => {:confirm => 'Are you sure to copy?'} ,:class=> "btn-close" ) %>

        <%= link_to(raw('<i class="halflings-icon remove"></i>'),survey_page_path(page.survey_id,page.id),remote: true, method: :delete, :data => {:confirm => 'Are you sure to delete?'} ,:class=> "btn-close" ) %>
        
      </div>
    </div>
    <div class="box-content">
      <div class="page-header">
        <h1><small><%=page.page_description%></small></h1>
      </div>
      <div class="row-fluid">
        <div class="priority low">
          <div class="btn-group">
            <button class="btn btn-medium dropdown-toggle btn-success" data-toggle="dropdown"> 
              <%= t(:add_element) %></button>
            <ul class="dropdown-menu right-menu">
              <li> <%= link_to(raw('Dropdown Question'),page_questions_path('dropdown',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('Dropdown Rangking'),page_questions_path('dropdown_rangking',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('Evaluation 1'),page_questions_path('evaluation1',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('Evaluation 2'),page_questions_path('evaluation2',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('file upload'),page_questions_path('file_upload',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('multiline_text_box'),page_questions_path('multiline_text_box',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('multiple_answer'),page_questions_path('multiple_answer',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('multiple_choices'),page_questions_path('multiple_choices',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('percentage'),page_questions_path('percentage',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('radio_box'),page_questions_path('radio_box',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('single_question'),page_questions_path('single_question',page.id),remote: true ) %></li>
              <li> <%= link_to(raw('yes_no'),page_questions_path('yes_no',page.id),remote: true ) %></li>
            </ul>
          </div>
        </div>
        <!-- #element page  -->
        <%= form_for(@question, :url => create_page_question_path(survey.id,page.id), :remote => true ,:html => { :method => :post, :role => 'form',:class => ""}) do |f| %>
          <div id="detail_element_<%=page.id%>" >
            <% page.questions.each_with_index do |pg,index| %>
              <%#= render :partial => "questions/list_#{pg.question_type}",:locals => {:question => pg,:index => index } %>
              <div class="task low" id="question_list_<%=pg.id%>">
                <%= render :partial => "questions/list_#{pg.question_type}",:locals => {:question => pg,:index => index,:proccessed_view => "" } %>
                <div class="time">
                  <div class="date">
                    <%= render :partial => "questions/actionPerQuestion" ,:locals => {:question => pg} %>
                  </div>
                  <div><%=pg.created_at.to_date%></div>
                </div>
              </div>
            <% end %>
          </div>
          <%= f.submit 'Save', :class => 'btn btn-primary hide save-btn' , :id => "save_question_#{page.id}" %>
        <%end%>
      </div>
    </div>
  </div><!--/span-->
</div>

app/views/pages/_detail_question.html.erb
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div data-original-title="" class="box-header">
      <h2>
        <i class="halflings-icon notes_2"></i>
        <span class="break"></span>
        <%= page.page_title %>
      </h2>
    </div>
    <div class="box-content">
      <div class="page-header">
        <h1><small><%= page.page_description %></small></h1>
      </div>
      <div class="row-fluid">
        <div id="detail_element_<%=page.id%>" >
          <% page.questions.each_with_index do |pg,index| %>
            <%= render :partial => "list_#{pg.question_type}",:locals => {:question => pg,:index => index } %>
          <% end %>
        </div>
      </div>
    </div>
  </div><!--/span-->
</div>

app/views/pages/_final_page_form.html.erb
<fieldset>
  <div class="control-group">
    <label class="control-label"><%= t(:custom_thank_you_page) %> <span class="mark-required">*</span></label>
    <div class="controls">
      <div class="input-prepend">
        <%= text_area_tag 'survey[final_page]', @survey.final_page, required: "required", style: 'width: 470px !important;height: 315px !important' %>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><%= t(:custom_redirect_upon_completion) %></label>
    <div class="controls">
      <div class="input-prepend"><%= text_field_tag 'survey[url_final_page]', @survey.url_final_page, style: 'width: 470px !important' %></div>
    </div>
  </div>
</fieldset>

app/views/pages/_form.html.erb
<fieldset>
  <div class="control-group">
    <label class="control-label">page title <span class="mark-required">*</span></label>

    <div class="controls">
      <div class="input-prepend">
        <%= text_field_tag 'page[page_title]',(page.blank? ? '' : page.page_title ), :autofocus => true , :required => "required"%>
        <%= hidden_field_tag 'page[id]',(page.blank? ? '' : page.id ), :autofocus => true , :required => "required"%>
        <%= hidden_field_tag 'page[survey_id]',(page.blank? ? '' : page.survey_id ), :autofocus => true , :required => "required"%>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">page description </label>

    <div class="controls">
      <div class="input-prepend">
        <%= text_area_tag 'page[page_description]',(page.blank? ? '' : page.page_description ), :autofocus => true%>
      </div>
    </div>
  </div>
</fieldset>

app/views/pages/_move.html.erb
<fieldset>
  <div class="control-group">
    <label class="control-label"> Survey </label>

    <div class="controls">
      <div class="input-prepend">
        <%#= text_area_tag 'page[page_description]',(page.blank? ? '' : page.page_description ), :autofocus => true%>
        <%= select_tag("move[survey_id]",options_from_collection_for_select(surveys,:id,:title)) %>
        <%= hidden_field_tag("move[type]",'true') %>
        <%= hidden_field_tag("move[page_id]",page_id) %>
      </div>
    </div>
  </div>
</fieldset>

app/views/pages/copy.js.erb
location.reload();

app/views/pages/create.js.erb
$('#pageForm').modal('hide');
location.reload();

app/views/pages/destroy.js.erb
// location.reload();

app/views/pages/edit.js.erb
$('#pageFormModal').modal('show');
$("#page_title_modal").html("Edit Page");
$("#page_modal_body_form").html('<%=escape_javascript(render :partial => "pages/form",:locals => {:page => @page}) %>');

app/views/pages/move.js.erb
$('#pageFormModal').modal('show');
$("#page_title_modal").html("Move Page");
$("#page_modal_body_form").html('<%=escape_javascript(render :partial => "pages/move",:locals => {:surveys => @surveys , :page_id => @page_id }) %>');

app/views/pages/page_questions.js.erb
var total = $(".wrapper_<%=@page_id%>").lenght + 1;
$("#detail_element_<%=@page_id%>").append("<%= escape_javascript(render partial: "questions/#{@type}" ,:locals => {:question => @question ,:page_id => @page_id , :index => @index})%>");
 
 $("#save_question_<%=@page_id%>").show();

app/views/pages/update.js.erb
$('#pageFormModal').modal('hide');
location.reload();