config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  
  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    # get 'login', to: "devise/sessions#new", as: "login"
    # get 'logout', to: "devise/sessions#destroy", as: "logout"
    # get 'logout', to: "users/sessions#destroy", as: "logout"
    get '/users/sign_out' => 'devise/sessions#destroy' 
    get 'signup', to: "users#new", as: "signup"
    # match '/users/:id', :to => 'users#show', :as => :user
  end

  resources :users
  # resources :surveys
  get "/testing", to: "surveys#testing"
  resources :surveys do
    resources :pages
    put :customize_final_page
    get :final_page
    get :fill
    post :post_answer
  end
  get '/page_question/:id/:page_id' ,to:  "pages#page_questions" ,:as => "page_questions"
  post 'save_page_question/:survey_id/:page_id' , to: "questions#create" , :as => "create_page_question"
  get 'questions/:id/destroy/:page_id' , to: "questions#destroy" , :as => "delete_question_page"
  get 'questions/:id/copy/:page_id' , to: "questions#copy" , :as => "copy_question_page"
  get 'questions/:id/edit/:page_id' , to: "questions#edit" , :as => "edit_question_page"
  put 'questions/update' , to: "questions#update" , :as => "update_question_page"
  get 'questions/:id/move/:page_id/:survey_id' , to: "questions#move" , :as => "move_question_page"
  put 'page/update' , to: "pages#update" , :as => "update_page"
  get 'page/:id/copy' , to: "pages#copy" , :as => "copy_page"
  get 'page/:id/move/:survey_id' , to: "pages#move" , :as => "move_page"
  get 'survey/:id/logical_workflow' , to: "surveys#logical_workflow" , :as => "logical_workflow_survey"
  post 'survey/:id/save_logical_workflow' , to: "surveys#save_logical_workflow" , :as => "save_logical_workflow_survey"
  get 'survey/:id/layout_coloring' , to: "surveys#layout_coloring" , :as => "layout_coloring_survey"
  post 'survey/:id/save_layout_coloring' , to: "surveys#save_layout_coloring" , :as => "save_layout_coloring_survey"
  post 'next_question_logical_workflow/:id/' , to: "surveys#next_question_logical_workflow" , :as => "next_question_logical_workflow"
  get 'customer_surveys/:id' , to: "customer_surveys#survey" , :as => "customer_survey"

  resources :reports 
  get 'report/:id/:type' , to: "reports#download" , :as => "download_reports"

  root to: 'visitors#index'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
	has_many :pages
	has_many :layout_colorings
	has_many :survey_answers
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token, :only => :next_question_logical_workflow

  def fill
    @survey = Survey.find(params[:survey_id])
  end

  def post_answer
    survey = Survey.find(params[:survey_id])
    status = SurveyAnswer.save_with_detail(params,current_user.id)
    final_page = survey.url_final_page.blank? ? (survey.final_page.blank? ? "/" : survey_final_page_path(params[:survey_id]) ) : survey.url_final_page
    redirect_to final_page , :notice => "Surveys success save"
  end

  def final_page
    @survey = Survey.find(params[:survey_id])
    render layout: false
  end

  def index
    @surveys = Survey.page(params[:page])
  end

  def testing
    render "surveys/new-evan"
  end

  def new
    @survey = Survey.new()
  end

  def create
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    survey_url = (0...50).map { o[rand(o.length)] }.join
    params[:survey][:survey_url] = survey_url
    
    survey = Survey.new(secure_params)
    if survey.save
      redirect_to :action => "index" , :notice => "save survey success created"
    else
      render :action => "new" , :alert => "save survey errors"
    end
  end

  def customize_final_page
    @survey = Survey.find(params[:survey_id])
    @survey.update_attributes(params.require(:survey).permit(:final_page, :url_final_page))
    respond_to do |format|
      format.js
    end
  end

  def show
    @survey = Survey.find(params[:id])
    @question = Question.new
    @page = Page.new()
  end

  def edit

  end

  def logical_workflow
    @survey = Survey.find(params[:id])
    @logical_dropdown,@logical_array = [] , []
    @survey.pages.each do |page|
      page.questions.each do |pq|
        if pq.question_type == "yes_no" || pq.question_type == "dropdown" || pq.question_type == "radio_box"
          @logical_dropdown << pq
          @logical_array << [pq.question , pq.id]
        end
      end
    end
  end

  def save_logical_workflow
    status = LogicalWorkflow.save_logical_workflow(params)
    if status
      redirect_to surveys_path, :notice => "Logical Workflow success created"
    else
      render logical_workflow , :alert => "Unable to update user."
    end
  end

  def layout_coloring
    @survey = Survey.find(params[:id])
    @layout_coloring = @survey.layout_colorings.first
  end

  def save_layout_coloring
    status,message = LayoutColoring.save_layout_coloring(params,params_coloring)
    if status
      redirect_to surveys_path, :notice => message
    else
      render layout_coloring , :alert => message
    end
  end

  def next_question_logical_workflow
    condition = {:question_id => params[:question_id],:choise_value => params[:choise_answer].first[1]}
    condition = {:question_id => params[:question_id],:choise_index => params[:choise_answer].first[1]} if params[:question_type] == "yes_no"

    lg = LogicalWorkflow.where(condition)
    render :json => lg.first
  end

  private
  def secure_params
    params.require(:survey).permit(:title, :initial_name, :language, :description,:survey_url)
  end

  def params_coloring
    params.require(:style).permit(:font_color,:background_color,:row_color,:button_font_color,:button_background_color,:button_border_color,:top_border_color,:bottom_border_color,:right_border_color,:left_border_color,:width_box,:height_box)
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_list_dropdown.html.erb
<div class="task low" id="question_list_<%=question.id%>">
  <div class="desc">
    <div class="title"> <%=index+1%>. <%=question.question%></div>
    <div>
      <%=generate_choise(question.question_type,question.choise)%>
    </div>
    <p><%=question.tooltips%></p>
  </div>
</div>

app/views/surveys/_list_evaluation1.html.erb
<div class="task low" id="question_list_<%= question.id %>">
  <div class="desc">
    <div class="title"> <%= index+1 %>. <%= question.question %></div>
    <div>
      <%= generate_choise(question.question_type, question) %>
    </div>
    <p><%= question.tooltips %></p>
  </div>
</div>

app/views/surveys/_list_evaluation2.html.erb
<div class="task low" id="question_list_<%=question.id%>">
  <div class="desc">
    <div class="title"> <%=index+1%>. <%=question.question%></div>
    <div>
      <%=generate_choise(question.question_type,question)%>
    </div>
    <p><%=question.tooltips%></p>
  </div>
</div>

app/views/surveys/_list_multiline_text_box.html.erb
<div class="task low" id="question_list_<%=question.id%>">
  <div class="desc">
    <div class="title"> <%=index+1%>. <%=question.question%></div>
    <div>
      <%=generate_choise(question.question_type,question)%>
    </div>
    <p><%=question.tooltips%></p>
  </div>
</div>

app/views/surveys/_list_multiple_answer.html.erb
<div class="task low" id="question_list_<%=question.id%>">
  <div class="desc">
    <div class="title"> <%=index+1%>. <%=question.question%></div>
    <div>
      <%=generate_choise(question.question_type,question)%>
    </div>
    <p><%=question.tooltips%></p>
  </div>
</div>

app/views/surveys/_list_yes_no.html.erb
<div class="task low" id="question_list_<%= question.id %>">
  <div class="desc">
    <div class="title"> <%= index+1 %>. <%= question.question %></div>
    <div>
      <%= generate_choise_for_answer_survey(question.question_type, question) %>
    </div>
    <p><%= question.tooltips %></p>
  </div>
</div>

app/views/surveys/_logical_view.html.erb
<% list_answers.each_with_index do |d,index| %>
  <span class="name"><%=d%> <%= hidden_field_tag "logical_workflow[choise_value][#{data.id}][#{index}]" , d %> </span>
  <span class="status"><%= select_tag "logical_workflow[choise][#{data.id}][#{index}]", options_for_select(logical_array,value_options["#{d}"]) ,:style => "width:100%;" ,:class=>"status"%> {<%=value_options%>} </span>
<%end%>

app/views/surveys/customize_final_page.js.erb
$('#pageFormModal').modal('hide');
location.reload();

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/fill.html.erb
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div data-original-title="" class="box-header">
      <h2><i class="halflings-icon edit"></i><span class="break"></span><%= t(:fill_survey) %></h2>
      <div class="box-icon">
        <a class="btn-setting" href="#"><i class="halflings-icon wrench"></i></a>
        <a class="btn-close" href="#"><i class="halflings-icon remove"></i></a>
      </div>
    </div>
    <div class="box-content">
      <%= render partial: 'surveys/info' %>
    </div>
  </div><!--/span-->
</div>
<div id="detail_page">
  <%= form_tag survey_post_answer_url(@survey) do %>
    <% @survey.pages.each do |page| %>
      <%= render partial: 'pages/detail_question',:locals => {:page => page, :survey => @survey} %>
    <% end %>
    <%= submit_tag t(:save), class: 'btn btn-primary save-btn' %>
  <% end %>
</div>

app/views/surveys/final_page.html.erb
<%= raw @survey.final_page %>

app/views/surveys/post_answer.js.erb
finalPage();

app/views/surveys/show.html.erb
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div data-original-title="" class="box-header">
      <h2><i class="halflings-icon edit"></i><span class="break"></span>Detail survey</h2>
      <div class="box-icon">
        <a class="btn-setting" href="#"><i class="halflings-icon wrench"></i></a>
        <a class="btn-close" href="#"><i class="halflings-icon remove"></i></a>
      </div>
    </div>
    <div class="box-content">
      <%= render partial: 'surveys/info'%>
    </div>
  </div><!--/span-->
</div>

<a class="btn btn-info btn-setting" id="add_page" href="#"><%= t(:add_page) %> </a>
<%= link_to t(:customize_final_page), '#', class: 'btn btn-info btn-setting customize_final_page' %>
<%= link_to t(:display_final_page), '#', class: 'btn btn-info btn-setting display_final_page' %>
<div id="detail_page">
  <% @survey.pages.each do |page| %>
    <%= render partial: 'pages/detail',:locals => {:page => page, :survey => @survey} %>
  <% end %>
</div>

<%= form_for(@page, :url => survey_pages_path(@survey.id) , :remote => true ,:html => { :role => 'form',:class => "form-horizontal" , 'data-model' => 'page'}) do |f| %>
  <div class="modal hide fade" id="pageForm">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>New Page</h3>
    </div>
    <div class="modal-body">
      <%= render partial: 'pages/form',:locals => {:f => f,:page => @page}%>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<%= form_for(@page, url: survey_customize_final_page_url(@survey.id) , remote: true, method: 'PUT', html: {role: 'form', class: "form-horizontal" , 'data-model' => 'page'}) do |f| %>
  <div class="modal hide fade" id="customize_final_page_form" style="width: 700px !important;height: 507px !important">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3><%= t(:customize_final_page) %></h3>
    </div>
    <div class="modal-body" style="height: 400px !important;max-height: 400px !important">
      <%= render partial: 'pages/final_page_form', locals: {:f => f,:page => @page}%>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<%= form_tag('/questions/update', remote: true , method: :put) do -%>
  <div class="modal hide fade" id="moveQuestionForm">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3 id="title_modal">Move Question</h3>
    </div>
    <div class="modal-body" id="modal_body_form">
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <input type="hidden" name="edit_question_id" id="edit_question_id"  value ="">
      <%= submit_tag 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<%end-%>


<%= form_tag(update_page_path, remote: true , method: :put,:class => "form-horizontal") do -%>
  <div class="modal hide fade" id="pageFormModal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3 id="page_title_modal">Page Modal</h3>
    </div>
    <div class="modal-body" id="page_modal_body_form">
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <%= submit_tag 'Save', :class => 'btn btn-primary' %>
    </div>
  </div>
<%end-%>

<div class="modal hide fade" id="display_final_page_form" style="width: 700px !important;height: 507px !important">
  <iframe src='http://localhost:3000/surveys/<%= @survey.id %>/final_page' width='100%' height='100%'></iframe>
</div>