config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  
  devise_for :users, :controllers => { :registrations => "users" }
  devise_scope :user do
    # get 'login', to: "devise/sessions#new", as: "login"
    # get 'logout', to: "devise/sessions#destroy", as: "logout"
    # get 'logout', to: "users/sessions#destroy", as: "logout"
    get '/users/sign_out' => 'devise/sessions#destroy' 
    get 'signup', to: "users#new", as: "signup"
    # match '/users/:id', :to => 'users#show', :as => :user
  end

  resources :users
  # resources :surveys
  get "/testing", to: "surveys#testing"
  resources :surveys do
    resources :pages
    put :customize_final_page
    get :final_page
    get :fill
    post :post_answer
  end
  get '/page_question/:id/:page_id' ,to:  "pages#page_questions" ,:as => "page_questions"
  post 'save_page_question/:survey_id/:page_id' , to: "questions#create" , :as => "create_page_question"
  get 'questions/:id/destroy/:page_id' , to: "questions#destroy" , :as => "delete_question_page"
  get 'questions/:id/copy/:page_id' , to: "questions#copy" , :as => "copy_question_page"
  get 'questions/:id/edit/:page_id' , to: "questions#edit" , :as => "edit_question_page"
  put 'questions/update' , to: "questions#update" , :as => "update_question_page"
  get 'questions/:id/move/:page_id/:survey_id' , to: "questions#move" , :as => "move_question_page"
  put 'page/update' , to: "pages#update" , :as => "update_page"
  get 'page/:id/copy' , to: "pages#copy" , :as => "copy_page"
  get 'page/:id/move/:survey_id' , to: "pages#move" , :as => "move_page"
  get 'survey/:id/logical_workflow' , to: "surveys#logical_workflow" , :as => "logical_workflow_survey"
  post 'survey/:id/save_logical_workflow' , to: "surveys#save_logical_workflow" , :as => "save_logical_workflow_survey"
  get 'survey/:id/layout_coloring' , to: "surveys#layout_coloring" , :as => "layout_coloring_survey"
  post 'survey/:id/save_layout_coloring' , to: "surveys#save_layout_coloring" , :as => "save_layout_coloring_survey"
  post 'next_question_logical_workflow/:id/' , to: "surveys#next_question_logical_workflow" , :as => "next_question_logical_workflow"
  get 'customer_surveys/:id' , to: "customer_surveys#survey" , :as => "customer_survey"

  resources :reports 
  get 'report/:id/:type' , to: "reports#download" , :as => "download_reports"

  root to: 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="index.html"><span>Esurvey</span></a>
      <!-- start: Header Menu -->
      <div class="nav-no-collapse header-nav">
        <ul class="nav pull-right">
          <!-- start: User Dropdown -->
          <li class="dropdown">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="halflings-icon white user"></i> <%=current_user.email%>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li class="dropdown-menu-title">
                <span>Account Settings</span>
              </li>
              <li>
                <%= link_to(raw('<i class="halflings-icon user"></i>Profile'),edit_user_path(current_user.id),"data-no-turbolink" => true)%>
              </li>
              <li>
                 <%= link_to(raw('<i class="halflings-icon off"></i> Logout'), destroy_user_session_path, :method => :delete,"data-no-turbolink" => true ) %>
              </li>
            </ul>
          </li>
          <!-- end: User Dropdown -->
        </ul>
      </div>
      <!-- end: Header Menu -->

    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-left" class="span2">
  <div class="nav-collapse sidebar-nav">
    <ul class="nav nav-tabs nav-stacked main-menu">
      <li><a href="/" data-no-turbolink><i class="icon-bar-chart"></i><span class="hidden-tablet"> Dashboard</span></a></li> 
      <li>
        <a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><span class="hidden-tablet"> Setting</span><span class="label label-important"> 3 </span></a>
        <ul>
          <li>
            <%= link_to(raw('<i class="icon-file-alt"></i><span class="hidden-tablet"> User</span>'), users_path,"data-no-turbolink" => true,:class => "submenu") %> 
          </li>
          <!-- <li><a class="submenu" href="submenu2.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Sub Menu 2</span></a></li>
          <li><a class="submenu" href="submenu3.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Sub Menu 3</span></a></li> -->
        </ul> 
      </li>
      <li>
        <%= link_to(raw('<i class="icon-list-alt"></i><span class="hidden-tablet"> Survey</span>'), surveys_path,"data-no-turbolink" => true) %> 
      </li>
      <li><%= link_to(raw('<i class="icon-edit"></i><span class="hidden-tablet"> Report</span>'), reports_path,"data-no-turbolink" => true) %>
      </li>

    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Esurvey" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Esurvey" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid-full">
      <div class="row-fluid">
      <%= render 'layouts/sidebar' %>
      <div id="content" class="span10">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Esurvey" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Esurvey" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application_login', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid-full">
      <div class="row-fluid">
         <%= render 'layouts/messages' %>
         <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/print_layout.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <%= wicked_pdf_stylesheet_link_tag('style', :media => :print) %>
    <%= stylesheet_link_tag 'application', media: :print%>

		<style type="text/css">
		.page-print {
		  width: "195mm";
		  height: "270mm"
		  page-break-after: "always";
		  overflow:"hidden";
		}

		.page-print .landscape-print {
		  position:"relative";
		  margin:"270mm 0";
		  width:"270mm";
		  height:"195mm";
		  -webkit-transform:"rotate(-90deg)";
		  -webkit-transform-origin:  "0mm 0mm";
		}
		</style>
		<script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
      }
    </script>

  </head>
  <body class="<%= controller_name %> <%= action_name%> page-print" onload="number_pages()">
    <%= yield %>
    
    <!-- Page <span class="page"></span> of <span class="topage"></span> -->
    
  </body>
</html>

app/views/layouts/survey.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Esurvey" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Esurvey" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application_login', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid-full">
      <div class="row-fluid">
         <%= render 'layouts/messages' %>
         <%= yield %>
      </div>
    </div>
  </body>
</html>